### ISSUE TITLE
onChanged(Integer integer) integer都有哪些值，啥意思？

### ISSUE THREAD

**Issue by yswheye** [txlbupt/VisibilityFragment#1]
public void onChanged(Integer integer) {
                Log.i("FragmentVisibility", "ParentFragment visibility:" + integer);
}

**Comment by txlbupt** [comment]
被hide了
    public static final int FRAGMENT_HIDDEN_STATE = 0x01;
tab被切走了
    public static final int USER_INVISIBLE_STATE = 0x02;
父Fragment隐藏了
    public static final int PARENT_INVISIBLE_STATE = 0x04;
生命周期pause
    public static final int LIFE_CIRCLE_PAUSE_STATE = 0x08;
以上是这个整形第一位到第四位的值为1时的含义
